### ISSUE TITLE
fill out example notebooks

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#199]
This is a parent issue, see individual issues below for details...

The following notebooks need to be filled out 
- [x] Run a pre-defined model #209
- [x] Compare models #344 
- [x] Add a model #360
- [x] Change the settings (parameters, discretisation or solver) #353
- [x] Add parameters #291 
- [x] Add a spatial method #238 
- [x] Add a solver #292 
- [x] Expression tree structure #200 
- [x] Lithium-ion models
  - [x] Single-Particle Model #209 
  - [x] Single-Particle Model with electrolyte #351
  - [x] Doyle-Fuller-Newman Model #352 
- [x] Lead-acid models #81 #344 
   - Full porous-electrode
   - Leading-Order Quasi-Static
   - Composite
- [x] Finite Volumes #238 
- ~~Inbuilt SciPy solver~~
- [x] scikits.odes solvers #292

**Comment by tinosulzer** [comment]
You mentioned some of these would be better as not notebooks (tutorials in the API docs?) - can we decide in this issue which examples should be notebooks and which should be something else?

**Comment by martinjrobins** [comment]
Yes, absolutely. Feel free to go through and edit this list.

I had a few ideas for an expression tree notebook, which is why I've started this issue (and #200). But I hadn't fully decided what notebooks we need and which ones would be better in the api docs

**Comment by rtimms** [comment]
looks like these are all done now. are there any extra examples we need at this moment in time @tinosulzer @Scottmar93 @martinjrobins ?

**Comment by tinosulzer** [comment]
Nope, happy to close this issue
