### ISSUE TITLE
more simplifications/optimisations

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#264]
Dumping some thoughts on more things that could be slowing down the evaluation of the tree and that we should try to optimise:
- [x] reshapes in `Multiplication` (see test and timings [here](https://github.com/pybamm-team/PyBaMM/blob/3007362a19efc0263cab8df71e4fa28296562139/tests/test_expression_tree/test_matrix.py#L101)) - PR #268 
- [ ] concatenations (some ideas [here](https://stackoverflow.com/questions/38470264/numpy-concatenate-is-slow-any-alternative-approach/38470331) about creating the array of the right size first? though we are doing this already for domain concatenation)
- [x] broadcast - use vector multiplication instead #381 
- [x] functions that are independent of input (e.g. [constant current function](pybamm/parameters/standard_current_functions/constant_current.py)) - PR #266 
- [x] repeated operations - issue #267 
- [x] `BoundaryValue(Broadcast(child))` simplifies to just `child`
- [x] experiment with writing out the expression tree as a python function #332

**Comment by tinosulzer** [comment]
Toy problem with simplifying (m1@(v1*(m2@v2)). 
Case 2: v1 is a state vector
Case 3: v1 is a constant vector
```
In [7]: expr2.render()                                                                                                                                                                                      
@
├── Matrix (300, 299)
└── *
    ├── y[0:299]
    └── @
        ├── Matrix (299, 300)
        └── y[0:300]

In [8]: expr2simp.render()                                                                                                                                                                                  
@
├── @
│   ├── Matrix (300, 299)
│   └── *
│       ├── y[0:299]
│       └── Matrix (299, 300)
└── y[0:300]

In [9]: %timeit expr2.evaluate(y=np.ones(300))                                                                                                                                                              
54.8 µs ± 4.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [10]: %timeit expr2simp.evaluate(y=np.ones(300))                                                                                                                                                         
1.7 ms ± 71.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [11]: expr3.render()                                                                                                                                                                                     
@
├── Matrix (300, 299)
└── *
    ├── Vector of length 299
    └── @
        ├── Matrix (299, 300)
        └── y[0:300]

In [12]: expr3simp.render()                                                                                                                                                                                 
@
├── Matrix (300, 300)
└── y[0:300]

In [13]: %timeit expr3.evaluate(y=np.ones(300))                                                                                                                                                             
54.4 µs ± 5.97 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [14]: %timeit expr3simp.evaluate(y=np.ones(300))                                                                                                                                                         
30.8 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
