### ISSUE TITLE
Speed up jacobian

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#315]
- [x] Simplify binary operations that involve matrices that are zero (by adapting `is_zero`) - #326 
- [x] Don't create new objects when evaluating the following - #325 
  - `Diagonal` (dense to sparse)
  - `SparseStack` (dense to sparse)
  - other binary operations (sparse to dense)
- [x] allow using `known_evals` dict - #318 
- [x] don't use jacobian in ODE models - the jacobian would be almost full anyway, and inverting the matrix (for implicit time-stepping) is easy, so the jacobian doesn't add anything

After #325 it looks like autograd might be the limiting step. Would there be a way to pre-compute the gradients?

**Comment by tinosulzer** [comment]
`PendingDeprecationWarning` is coming from sparse - numpy operation (converts sparse matrix to numpy array)
