### ISSUE TITLE
Reduce the number of deepcopies in the workflow

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/PyBaMM#329]
These are very slow (usually account for ~60% of total runtime)

- [x] Alternative for setting parameters - #330 
    - Create a new object instead of copying in the cases where no parameters are to be set ([this line](https://github.com/pybamm-team/PyBaMM/blob/cefbaeda1736de76c5275cc68aa2fb6e2fb8aa8a/pybamm/parameters/parameter_values.py#L247))? TBC whether this will be faster
- [x] Alternative for discretising - #330 
   - As above
- [x] Alternative for simplifying
- [x] Alternative for `orphans` - seems difficult but the above three are the priority - #403

**Comment by tinosulzer** [comment]
I've done this for parameter values and discretisation and it makes a difference.
Not immediately obvious how to do this for simplification. The main issue is that we do a deepcopy of the whole tree at each level. It might make more sense to have an external class that does the simplification, similarly to setting parameter values and discretising; this could get called by `Symbol.simplify()` so that this functionality remains

**Comment by martinjrobins** [comment]
Yup, as per slack discussion I think this would be a good idea, so go ahead @tinosulzer

**Comment by tinosulzer** [comment]
To overwrite the `orphans`, we could make our own equivalent of `deepcopy` that just iteratively creates a new object (I guess this doesn't do *quite* the same thing as `deepcopy` so we should call it something else, maybe `new_instance` or something)
