### ISSUE TITLE
Tracking issue for improvements to `install_KLU_Sundials.py` and build infrastructure

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/PyBaMM#3651]
> [!WARNING]
> Following an imminent migration for the build system and/or choice of build-backend for PyBaMM, not all of the listed points may not be applicable for completion. Please refer to #3564 for more information.

There are a number of improvements that can be introduced to improve the installation of the build-time dependencies (SuiteSparse and SUNDIALS) and the IDAKLU extension module and general improvements to the installation scripts:

- [x] Incorporate the SHA-256 hashes of the SuiteSparse and SUNDIALS release tarballs as constants in the script in order to save bandwidth and skip downloading the tarball every time. (#3719)
- [x] Do not install locally if the binaries are already present at the installation location (#3418) (#3719)
- [x] Set parallel builds via the use of the `CMAKE_BUILD_PARALLEL_LEVEL` environment variable (#3646)
- [x] Introduce PEP 723 support (needs triage and should be reviewed at a later time in 2024) (#3647) (#3716)
- [ ] Establish local SUNDIALS and SuiteSparse installations in a folder `sundials_installed/` by adjusting `CMAKE_INSTALL_PREFIX` instead of modifying the `.local/` folder and check this folder to establish whether the IDAKLU extension module should be compiled or not in the `build_ext` command class in `setup.py` (adding `pybind11` as a build-time dependency should be possible in #3480 after this)
- [ ] Build just IDAS instead of all SUNDIALS components, considering that is what we link to for the IDAKLU target
- [ ] Set relevant SUNDIALS and SuiteSparse compilation options such as skipping building the examples (done in #3569), link to OpenBLAS instead of Apple's Accelerate on macOS since NumPy and SciPy are not recommending it for now
- [ ] On macOS, we use compiler options to find `libomp`, they can be removed and we can use `pkg-config` from Homebrew that should be able to do it automatically. The reason for this is because Apple Clang does not come with the OpenMP specification – however, other compilers such as LLVM and GCC do (noted by @kratman: we install `gcc` in CI for macOS, but it is never used!)
- [x] Remove `wget` as a dependency and use `urllib` from the Python standard library for downloading. In addition to this, use `multiprocessing.Pool` or `concurrent.futures` to download both tarballs in parallel to save time (#3719)
- [ ] On platforms we don't support, the `sdist` is used to install PyBaMM, and the IDAKLU solver which is optional cannot be installed unless installing from source. To provide a means to attempt IDAKLU compilation, a `--extra-options` command-line flag can be added to the `pip install pybamm` comand that can pass to `setup.py`. Therefore, the users should have to manually opt-in to the compilation (the build option should be off by default). For this, `pybind11` should be a build-time dependency (see #3480). This requires the points mentioned below:
- [ ] Run `install_KLU_Sundials.py` in a subprocess via a `build_py` command class for macOS and Linux in `setup.py` if the compilation is opted in for. This can eliminate the use of `nox -s pybamm-requires` and a single command `pip install -e .` would do both things
- [ ] Add `CMakeLists.txt` and other relevant files such as `FindSuiteSparse.cmake` and `FindSUNDIALS.cmake` to the SDist via the `MANIFEST.in` file, otherwise CMake will raise an error about a missing project status

These tasks have a mixture of easy and medium difficulty. Some of them have a higher priority than the rest, I am glad to take those up myself.

**Comment by agriyakhetarpal** [comment]
Closing this issue and moving individual remaining items over to #3564 – they can be tracked better there and that issue is now more relevant to the discussion.
