### ISSUE TITLE
testing TODO

### ISSUE THREAD

**Issue by martinjrobins** [pybamm-team/PyBaMM#69]
- general convergence test
- test convergence of complicated model to simple
- analytical solutions to specific models
- method of manufactured solutions

**Comment by tinosulzer** [comment]
Have started adding manufactured solution, to do:
- [ ] explain MMS in `ManufacturedSolution` docstring
- [ ] finish testing the behaviour of `ManufacturedSolution` on known (easy) models
- [ ] set up standard MMS convergence test for models (ideally after #279 merged)
- [ ] figure out how to do explicit integral: code up some very simple cases, or always provide explicitly?

**Comment by martinjrobins** [comment]
@tinosulzer : is this finished now?

**Comment by tinosulzer** [comment]
I was working on using Method of Manufactured Solutions to check convergence, there were some problems with it and I don't think this is a priority any more and if we wanted to we could just check error relative to the finest mesh. There might be some stuff to merge in this branch though so I will check

**Comment by tinosulzer** [comment]
Unlikely to be done any time soon; closing
